add android14-6.1.145

diff --git a/kernel/scripts/Makefile.modpost b/kernel/scripts/Makefile.modpost
--- a/kernel/scripts/Makefile.modpost
+++ b/kernel/scripts/Makefile.modpost
@@ -35,38 +35,23 @@
 PHONY := __modpost
 __modpost:
 
-include $(objtree)/include/config/auto.conf
+include include/config/auto.conf
 include $(srctree)/scripts/Kbuild.include
 
 mixed-build-prefix = $(if $(KBUILD_MIXED_TREE),$(KBUILD_MIXED_TREE)/)
 
-MODPOST = $(objtree)/scripts/mod/modpost
-
 modpost-args =										\
-	$(if $(CONFIG_MODULES),-M)							\
 	$(if $(CONFIG_MODVERSIONS),-m)							\
-	$(if $(CONFIG_BASIC_MODVERSIONS),-b)						\
-	$(if $(CONFIG_EXTENDED_MODVERSIONS),-x)						\
 	$(if $(CONFIG_MODULE_SRCVERSION_ALL),-a)					\
 	$(if $(CONFIG_SECTION_MISMATCH_WARN_ONLY),,-E)					\
-	$(if $(KBUILD_MODPOST_WARN),-w)							\
-	$(if $(KBUILD_NSDEPS),-d modules.nsdeps)					\
+	$(if $(KBUILD_NSDEPS),-d $(MODULES_NSDEPS))					\
 	$(if $(CONFIG_MODULE_ALLOW_MISSING_NAMESPACE_IMPORTS)$(KBUILD_NSDEPS),-N)	\
 	$(if $(findstring 1, $(KBUILD_EXTRA_WARN)),-W)					\
 	-o $@
 
-modpost-deps := $(MODPOST)
-
 # 'make -i -k' ignores compile errors, and builds as many modules as possible.
 ifneq ($(findstring i,$(filter-out --%,$(MAKEFLAGS))),)
 modpost-args += -n
-endif
-
-# Read out modules.order to pass in modpost.
-# Otherwise, allmodconfig would fail with "Argument list too long".
-ifdef KBUILD_MODULES
-modpost-args += -T modules.order
-modpost-deps += modules.order
 endif
 
 ifeq ($(CONFIG_MODULE_SCMVERSION),y)
@@ -103,7 +88,9 @@ ifeq ($(KBUILD_EXTMOD),)
 
 # This is used to retrieve symbol versions generated by genksyms.
 ifdef CONFIG_MODVERSIONS
+ifndef KBUILD_MIXED_TREE
 vmlinux.symvers Module.symvers: .vmlinux.objs
+endif
 endif
 
 # Ignore libgcc.a
@@ -119,72 +106,84 @@ quiet_cmd_vmlinux_objs = GEN     $@
 		esac			\
 	done > $@
 
+quiet_cmd_vmlinux_symvers = GEN     $@
+      cmd_vmlinux_symvers = grep "\<vmlinux\s\+EXPORT" $< > $@
+
+quiet_cmd_cat_symvers = GEN     $@
+      cmd_cat_symvers = cat $(real-prereqs) > $@
+
+ifndef KBUILD_MIXED_TREE
 targets += .vmlinux.objs
 .vmlinux.objs: vmlinux.a $(KBUILD_VMLINUX_LIBS) FORCE
 	$(call if_changed,vmlinux_objs)
-
-ifdef CONFIG_TRIM_UNUSED_KSYMS
-ksym-wl := $(CONFIG_UNUSED_KSYMS_WHITELIST)
-ksym-wl := $(if $(filter-out /%, $(ksym-wl)),$(if $(wildcard $(ksym-wl)),,$(srctree)/))$(ksym-wl)
-modpost-args += -t $(addprefix -u , $(ksym-wl))
-modpost-deps += $(ksym-wl)
 endif
 
-ifeq ($(wildcard vmlinux.o),)
+vmlinux.o-if-present := $(wildcard vmlinux.o)
+output-symdump := vmlinux.symvers
 
-# ANDROID: Use vmlinux.symvers from base build when doing mixed build
-ifneq ($(wildcard vmlinux.symvers),)
-modpost-args += -i vmlinux.symvers
-# Not adding vmlinux.symvers to modpost-deps to avoid dependency on
-#   .vmlinux.objs. Just use the one from base build.
-# Note: we don't want to include the vmlinux symbols here because we want to be
-# sure we only use the vmlinux symbols from the GKI kernel.
-output-symdump := modules-only.symvers
-else # vmlinux.symvers does not exist
-missing-input := vmlinux.o
-output-symdump := modules-only.symvers
-endif # whether vmlinux.symvers exists
+ifdef KBUILD_MODULES
+output-symdump := $(if $(vmlinux.o-if-present), Module.symvers, modules-only.symvers)
+missing-input := $(filter-out $(vmlinux.o-if-present),vmlinux.o)
 
-else
-modpost-args += vmlinux.o
-modpost-deps += vmlinux.o
-output-symdump := $(if $(KBUILD_MODULES), Module.symvers, vmlinux.symvers)
+targets += vmlinux.symvers
+vmlinux.symvers: Module.symvers FORCE
+	$(call if_changed,vmlinux_symvers)
+
+__modpost: $(if $(vmlinux.o-if-present),vmlinux.symvers,)
+endif
+
+# Overwrite values for mixed building (overwritting makes merges easier)
+ifdef KBUILD_MIXED_TREE
+targets += Module.symvers
+Module.symvers: $(mixed-build-prefix)vmlinux.symvers modules-only.symvers FORCE
+	$(call if_changed,cat_symvers)
+
+__modpost: Module.symvers
+
+vmlinux.o-if-present :=
+vmlinux.symvers-if-present := $(wildcard $(mixed-build-prefix)vmlinux.symvers)
+modpost-args += $(addprefix -i ,$(vmlinux.symvers-if-present))
+output-symdump := modules-only.symvers
+missing-input := $(filter-out $(vmlinux.symvers-if-present),$(mixed-build-prefix)vmlinux.symvers)
 endif
 
 else
 
 # set src + obj - they may be used in the modules's Makefile
-obj := .
-src := $(srcroot)
+obj := $(KBUILD_EXTMOD)
+src := $(obj)
 
 # Include the module's Makefile to find KBUILD_EXTRA_SYMBOLS
-include $(kbuild-file)
+include $(or $(wildcard $(src)/Kbuild), $(src)/Makefile)
 
-output-symdump := Module.symvers
+module.symvers-if-present := $(wildcard Module.symvers)
+output-symdump := $(KBUILD_EXTMOD)/Module.symvers
+missing-input := $(filter-out $(module.symvers-if-present), Module.symvers)
 
-ifeq ($(wildcard $(objtree)/Module.symvers),)
-missing-input := $(objtree)/Module.symvers
-else
-modpost-args += -i $(objtree)/Module.symvers
-modpost-deps += $(objtree)/Module.symvers
-endif
-
-modpost-args += -e $(addprefix -i , $(KBUILD_EXTRA_SYMBOLS))
+modpost-args += -e $(addprefix -i ,$(module.symvers-if-present) $(KBUILD_EXTRA_SYMBOLS))
 
 endif # ($(KBUILD_EXTMOD),)
 
+ifneq ($(KBUILD_MODPOST_WARN)$(missing-input),)
+modpost-args += -w
+endif
+
+modorder-if-needed := $(if $(KBUILD_MODULES), $(MODORDER))
+
+MODPOST = scripts/mod/modpost
+
+# Read out modules.order to pass in modpost.
+# Otherwise, allmodconfig would fail with "Argument list too long".
 quiet_cmd_modpost = MODPOST $@
       cmd_modpost = \
 	$(if $(missing-input), \
 		echo >&2 "WARNING: $(missing-input) is missing."; \
 		echo >&2 "         Modules may not have dependencies or modversions."; \
-		echo >&2 "         You may get many unresolved symbol errors."; \
-		echo >&2 "         You can set KBUILD_MODPOST_WARN=1 to turn errors into warning"; \
-		echo >&2 "         if you want to proceed at your own risk.";) \
-	$(MODPOST) $(modpost-args)
+		echo >&2 "         You may get many unresolved symbol warnings.";) \
+	sed 's/ko$$/o/' $(or $(modorder-if-needed), /dev/null) | $(MODPOST) $(modpost-args) -T - $(vmlinux.o-if-present)
 
 targets += $(output-symdump)
-$(output-symdump): $(modpost-deps) FORCE
+$(output-symdump): $(modorder-if-needed) $(vmlinux.o-if-present) $(module.symvers-if-present) $(MODPOST) FORCE
 	$(call if_changed,modpost)
 
 __modpost: $(output-symdump)
